with pkg from (mapcar (lambda (s) (list (package-name s) s)) (list-all-packages))
file "::nicknames" (fmt "~{~a~%~}" (package-nicknames pkg))
file "::uses" (fmt "~{~a~%~}" (package-use-list pkg))
file "::used-by" (fmt "~{~a~%~}" (package-used-by-list pkg))
with symb from (loop for s being each present-symbol in pkg collect (list (symbol-name s) s))
file "::documentation" (with-output-to-string (s) (describe symb s))
file "::package" (package-name (symbol-package symb))
file "::boundp" (fmt "~a~%" (boundp symb))
file "::fboundp" (fmt "~a~%" (fboundp symb))
sink "::contents" (fmt "~s~%" (ignore-errors (symbol-value symb)))
(data 
  (let* ((str (ignore-errors (cl-fuse::octets-to-string data :full-range)))
         (code (ignore-errors (with-input-from-string (s str) (read s))))
         )
        (set symb code)))
